# Generated by Django 5.1.1 on 2024-09-15 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='purch_qty',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='sale_qty',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='total_bal_qty',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.unit'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_amnt',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='sales',
            name='total_amnt',
            field=models.FloatField(editable=False),
        ),
    ]
